### ISSUE TITLE
Tests failing with new version of XCode

### ISSUE THREAD

**Issue by drazisil** [codecov/swift-standard#1]
https://www.diffchecker.com/l0WjGgKo

Passing build, https://travis-ci.org/codecov/Swift-Standard/builds/567033497 on the right.

With the failing builds, coverage dropped and repo no longer passed.

**Comment by ibrahim0814** [comment]
Build is now passing 

This was an issue with the ui tests which failed because they were not able to find the proper button labels. Added new button labels corresponding to the updated version of Xcode, thanks @drazisil :)
