### ISSUE TITLE
The guide for adding code coverage for iOS Swift and upload to Codecov

### ISSUE THREAD

**Issue by hongbo-miao** [codecov/swift-standard#18]
I spent two days doing a lot of experiments to add code coverage for a new iOS Swift app and upload to Codecov.
To save some time for future people who wants to add same thing,
here is my the pull request which you can see the code I added to make it work: https://github.com/Hongbo-Miao/hongbomiao.com/pull/6134
Hopefully it helps! 😃

**Comment by thomasrockhu** [comment]
Thanks for this @Hongbo-Miao! I'll look into how to ingest this, and thanks for the help
